/* GESMS V10.0 Beta - prayer target Excel ministry module */
(function(){
'use strict';
const FILES=['기도대상자관리_표준양식_V2.0.xlsx','기도대상자관리.xlsx'];
const STAGES=[['기도중','기도중'],['관계형성','관계형성'],['첫만남','첫만남'],['초청','초청'],['교회방문','교회방문'],['새가족','새가족'],['등록교인','등록교인'],['군우편입','군우편입']];
const $=s=>document.querySelector(s), text=v=>String(v??'').trim(), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pad=n=>String(n).padStart(2,'0');
let targets=[];
function excelDate(v){if(v===null||v===undefined||v==='')return '';if(typeof v==='string'&&/^\d{4}[-/.]\d{1,2}[-/.]\d{1,2}/.test(v)){const m=v.match(/(\d{4})[-/.](\d{1,2})[-/.](\d{1,2})/);return `${m[1]}-${pad(m[2])}-${pad(m[3])}`;}const n=Number(v);if(!Number.isFinite(n))return text(v);const d=new Date(Date.UTC(1899,11,30)+Math.round(n*86400000));return `${d.getUTCFullYear()}-${pad(d.getUTCMonth()+1)}-${pad(d.getUTCDate())}`;}
function colIndex(ref){let n=0;for(const ch of (ref.match(/[A-Z]+/i)||['A'])[0].toUpperCase())n=n*26+ch.charCodeAt(0)-64;return n-1;}
async function parseXlsx(buffer){const zip=await JSZip.loadAsync(buffer);const sx=zip.file('xl/sharedStrings.xml');const shared=[];if(sx){const doc=new DOMParser().parseFromString(await sx.async('text'),'application/xml');[...doc.getElementsByTagNameNS('*','si')].forEach(si=>shared.push([...si.getElementsByTagNameNS('*','t')].map(t=>t.textContent||'').join('')))}const wbxml=zip.file('xl/workbook.xml');let sheetPath='xl/worksheets/sheet1.xml';if(wbxml){const doc=new DOMParser().parseFromString(await wbxml.async('text'),'application/xml');const sheets=[...doc.getElementsByTagNameNS('*','sheet')];const wanted=sheets.find(x=>x.getAttribute('name')==='기도대상자관리');if(wanted){const rid=wanted.getAttributeNS('http://schemas.openxmlformats.org/officeDocument/2006/relationships','id')||wanted.getAttribute('r:id');const rel=zip.file('xl/_rels/workbook.xml.rels');if(rel&&rid){const rdoc=new DOMParser().parseFromString(await rel.async('text'),'application/xml');const rr=[...rdoc.getElementsByTagNameNS('*','Relationship')].find(x=>x.getAttribute('Id')===rid);if(rr)sheetPath='xl/'+rr.getAttribute('Target').replace(/^\/?xl\//,'')}}}const sf=zip.file(sheetPath)||zip.file('xl/worksheets/sheet1.xml');if(!sf)throw new Error('기도대상자관리 시트를 찾지 못했습니다.');const doc=new DOMParser().parseFromString(await sf.async('text'),'application/xml');const rows=[];[...doc.getElementsByTagNameNS('*','row')].forEach(row=>{const out=[];[...row.getElementsByTagNameNS('*','c')].forEach(c=>{const idx=colIndex(c.getAttribute('r')||'A1'),type=c.getAttribute('t'),v=c.getElementsByTagNameNS('*','v')[0]?.textContent??'';let value=v;if(type==='s')value=shared[Number(v)]??'';else if(type==='inlineStr')value=[...c.getElementsByTagNameNS('*','t')].map(t=>t.textContent||'').join('');out[idx]=value});rows[Number(row.getAttribute('r')||rows.length+1)-1]=out});return rows;}
function rowsToTargets(rows){let hi=-1,headers=[];for(let i=0;i<Math.min(rows.length,20);i++){const a=(rows[i]||[]).map(text);if(a.includes('관리번호')&&a.includes('이름')&&a.includes('담당자')){hi=i;headers=a;break}}if(hi<0)throw new Error('관리번호·이름·담당자 열을 찾지 못했습니다.');const ix=n=>headers.indexOf(n),out=[];for(let i=hi+1;i<rows.length;i++){const r=rows[i]||[],name=text(r[ix('이름')]);if(!name)continue;const use=text(r[ix('사용여부')]);if(use==='미사용')continue;const o={};headers.forEach((h,j)=>o[h]=r[j]);['기도시작일','최근만남일','다음연락일','교회방문일','새가족등록일','등록교인일','군우편입일','기도응답일'].forEach(k=>o[k]=excelDate(o[k]));out.push(o)}return out;}
async function fetchDefault(){let last='';for(const name of FILES){try{const r=await fetch('./'+encodeURIComponent(name)+'?v='+Date.now(),{cache:'no-store'});if(!r.ok){last=`${name}: HTTP ${r.status}`;continue}return {name,rows:await parseXlsx(await r.arrayBuffer())}}catch(e){last=e.message||String(e)}}throw new Error(last||'기도대상자 Excel을 불러오지 못했습니다.');}
function y(o,k){return text(o[k]).toUpperCase()==='Y';}
function currentStage(o){for(let i=STAGES.length-1;i>=0;i--)if(y(o,STAGES[i][0]))return STAGES[i][1];return '기도 준비';}
function getGoal(){return Math.max(1,Number(localStorage.getItem('gesms_soul_goal')||100));}
function filtered(){const q=text($('#prayerSearch')?.value).toLowerCase(),owner=text($('#prayerOwner')?.value),group=text($('#prayerGroup')?.value),state=text($('#prayerState')?.value);return targets.filter(o=>{const hay=[o['이름'],o['담당자'],o['관계구분'],o['관계상세'],o['기도제목구분'],o['기도제목상세'],o['소속부서/소그룹']].map(text).join(' ').toLowerCase();return(!q||hay.includes(q))&&(!owner||text(o['담당자'])===owner)&&(!group||text(o['소속부서/소그룹'])===group)&&(!state||text(o['진행상태'])===state)});}
function daysFrom(date){if(!date)return null;const a=new Date(date+'T00:00:00'),b=new Date();b.setHours(0,0,0,0);return Math.round((a-b)/86400000);}
function renderFilters(){const owners=[...new Set(targets.map(o=>text(o['담당자'])).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ko'));const groups=[...new Set(targets.map(o=>text(o['소속부서/소그룹'])).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ko'));const fill=(sel,arr,label)=>{if(!sel)return;const old=sel.value;sel.innerHTML=`<option value="">${label}</option>`+arr.map(v=>`<option>${esc(v)}</option>`).join('');sel.value=old};fill($('#prayerOwner'),owners,'모든 담당자');fill($('#prayerGroup'),groups,'모든 소그룹');}
function renderStats(){const goal=getGoal(),counts={};STAGES.forEach(([k])=>counts[k]=targets.filter(o=>y(o,k)).length);const current=targets.length,visit=counts['교회방문'],newc=counts['새가족'],registered=counts['등록교인'];$('#soulGoal').value=goal;$('#soulGoalKpi').textContent=goal;$('#soulCurrentKpi').textContent=current;$('#soulVisitKpi').textContent=visit;$('#soulNewKpi').textContent=newc;const max=Math.max(1,...Object.values(counts));$('#soulStageChart').innerHTML=STAGES.map(([k,l])=>`<div class="stage-row"><span>${l}</span><i style="width:${counts[k]/max*100}%"></i><b>${counts[k]}</b></div>`).join('');const rate=Math.min(100,Math.round(registered/goal*100));$('#soulSummaryText').innerHTML=`현재 <b>${current}명</b>을 위해 기도하며, 등록교인 <b>${registered}명</b>으로 연간 목표의 <b>${rate}%</b>를 이루었습니다.`;$('#homeSoulProgress').textContent=`${registered}/${goal}명 · ${rate}%`;$('#homeSoulMeta').textContent=`기도대상 ${current}명 · 교회방문 ${visit}명 · 새가족 ${newc}명`;const today=targets.filter(o=>text(o['진행상태'])==='계속기도').slice(0,5);$('#homePrayerCount').textContent=`${targets.filter(o=>text(o['진행상태'])==='계속기도').length}명`;$('#homePrayerNames').textContent=today.length?today.map(o=>text(o['이름'])).join(', '):'등록된 계속기도 대상자가 없습니다.';const contacts=targets.filter(o=>{const d=daysFrom(o['다음연락일']);return d!==null&&d>=0&&d<=7}).sort((a,b)=>text(a['다음연락일']).localeCompare(text(b['다음연락일'])));$('#homeContactCount').textContent=`${contacts.length}명`;$('#homeContactNames').textContent=contacts.length?contacts.slice(0,4).map(o=>`${text(o['이름'])}(${o['다음연락일'].slice(5)})`).join(', '):'7일 이내 연락 대상이 없습니다.';}
function renderList(){const list=filtered();$('#prayerCount').textContent=`${list.length}명`;$('#prayerList').innerHTML=list.length?list.map((o,i)=>{const stage=currentStage(o),phone=text(o['연락처']),contact=o['다음연락일']?`다음 연락 ${o['다음연락일']}`:'다음 연락 미정';return `<article class="prayer-person"><div class="prayer-head"><div class="prayer-avatar">${esc(text(o['이름']).slice(0,1))}</div><div><h4>${esc(o['이름'])}</h4><p>담당 ${esc(o['담당자']||'-')} · ${esc(o['소속부서/소그룹']||'소속 미정')} · ${esc(contact)}</p></div><span class="stage-badge">${esc(stage)}</span></div><div class="prayer-detail"><div class="detail-grid"><div><span>관계</span><b>${esc([o['관계구분'],o['관계상세']].filter(Boolean).join(' · ')||'-')}</b></div><div><span>연락처</span><b>${esc(phone||'-')}</b></div><div><span>기도 시작</span><b>${esc(o['기도시작일']||'-')}</b></div><div><span>최근 만남</span><b>${esc(o['최근만남일']||'-')}</b></div><div><span>다음 연락</span><b>${esc(o['다음연락일']||'-')}</b></div><div><span>진행상태</span><b>${esc(o['진행상태']||'-')}</b></div></div><div class="prayer-topic"><b>${esc(o['기도제목구분']||'기도제목')}</b><br>${esc(o['기도제목상세']||'-')}</div><div class="stage-pills">${STAGES.map(([k,l])=>`<span class="${y(o,k)?'done':''}">${y(o,k)?'✓ ':''}${l}</span>`).join('')}</div>${text(o['비고'])?`<div class="prayer-topic" style="border-color:var(--navy);background:#eef3f8"><b>비고</b><br>${esc(o['비고'])}</div>`:''}</div></article>`}).join(''):'<div class="no-results">조건에 맞는 기도대상자가 없습니다.</div>';document.querySelectorAll('.prayer-head').forEach(x=>x.onclick=()=>x.parentElement.classList.toggle('open'));}
function setStatus(msg,error=false){const el=$('#prayerExcelStatus');if(!el)return;el.textContent=msg;el.classList.toggle('error',error);}
function apply(rows,name){targets=rowsToTargets(rows);window.PRAYER_TARGETS=targets;renderFilters();renderStats();renderList();setStatus(`${name} · ${targets.length}명 · ${new Date().toLocaleTimeString('ko-KR')} 확인`);}
async function load(){setStatus('기도대상자 Excel 최신 파일을 확인하는 중입니다.');try{const x=await fetchDefault();apply(x.rows,x.name)}catch(e){targets=[];renderFilters();renderStats();renderList();setStatus(`자동 불러오기 실패: ${e.message||e} · 설정에서 파일명을 확인하세요.`,true)}}
window.initPrayerMinistry=function(){['prayerSearch','prayerOwner','prayerGroup','prayerState'].forEach(id=>{const el=$('#'+id);if(el)el.addEventListener(id==='prayerSearch'?'input':'change',renderList)});$('#refreshPrayerExcel')?.addEventListener('click',load);$('#saveSoulGoal')?.addEventListener('click',()=>{localStorage.setItem('gesms_soul_goal',Math.max(1,Number($('#soulGoal').value||100)));renderStats()});$('#selectPrayerExcel')?.addEventListener('click',()=>$('#prayerExcelInput').click());$('#prayerExcelInput')?.addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{apply(await parseXlsx(await f.arrayBuffer()),f.name)}catch(err){setStatus(`파일 읽기 실패: ${err.message||err}`,true)}});$('#downloadPrayerTemplate')?.addEventListener('click',()=>{location.href='./'+encodeURIComponent('기도대상자관리_표준양식_V2.0.xlsx')});load();};
})();
